### ISSUE TITLE
json file format for log_activity 

### ISSUE THREAD

**Issue by tenderitaf** [orcasgit/python-fitbit#101]
Hi,
I'm trying to use log_activity function but bad request exception is always caught 
`fitbit.exceptions.HTTPBadRequest: Either "activityId" or "activityName" should be present`

my json file is the same one as in the api example 
`{
    "activityLog":{
        "activityId":12030,
        "activityParentId":90009,
        "calories":197,
        "description":"5 mph (12 min/mile)",
        "distance":3.34,
        "duration":1800000,
        "isFavorite":false,
        "logId":132394,
        "name":"Running",
        "startTime":"12:20",
        "steps":2970
   }
}`

how I read the file 

`    data = []
    with open('log_activity') as f:
         data = json.load(f)
    print(data)
authd_client.log_activity(data)
`
is there any issue with my code/file
thanks a lot

**Comment by brad** [comment]
@tenderitaf Try `authd_client.log_activity(data['activityLog'])`

Still, some of your parameters aren't right. Your json file is an example of what fitbit will respond with after you post an activity log. Your POST should have these parameters:

POST Parameters
----------------------------

**activityId**	_optional/required_	This is the Activity ID of the activity, directory activity, or intensity level activity. If you pass directory activity id, Fitbit calculates and substitutes it with the corresponding intensity level activity id based on the specified distance and/or duration.

**activityName**	_optional/required_	Custom activity name. Either activityId or activityName must be provided.

**manualCalories**	_optional/required_	Calories burned, specified manually. Required with activityName parameter, otherwise optional.

**startTime**	_required_	Activity start time. Hours and minutes in the format HH:mm:ss.

**durationMillis**	_required_	Duration in milliseconds.

**date**	_required_	Log entry date; in the format yyyy-MM-dd.

**distance**	_optional/required_	Distance; required for logging directory activity. In the format X.XX and in the selected distanceUnit or in the unit system that corresponds to the Accept-Language header provided.

**distanceUnit**	_optional_	Distance measurement unit. Steps units are available only for "Walking" (activityId=90013) and "Running" (activityId=90009) directory activities and their intensity levels.
```

**Comment by tenderitaf** [comment]
Thanks a lot it worked :)
