### ISSUE TITLE
Add ability to log body measurements

### ISSUE THREAD

**Issue by git-commit** [orcasgit/python-fitbit#54]
I would like to use the api to add some body measurements (e.g. weight).

See:
https://wiki.fitbit.com/display/API/API-Log-Body-Measurements

**Comment by brad** [comment]
Hi @git-commit 
You can add body measurements using the `body` method, described here:
http://python-fitbit.readthedocs.org/en/stable/#fitbit.Fitbit._COLLECTION_RESOURCE

Sorry, the documentation is a little confusing because those methods are defined using `setattr` at runtime. Please reopen this if that doesn't work.
